### ISSUE TITLE
Frequent incomplete image buffer warnings

### ISSUE THREAD

**Issue by wiewo** [roboception/rc_visard_ros#10]
Hi,

when subscribing to the `points2` topic, the driver shows the following warning quite a lot:
```
rc_visard_driver: Received incomplete image buffer
````
It's certainly not for every received buffer, but roughly every two or three seconds, a new buffer warning pops up. Is this more or less an expected behavior or is there maybe something wrong, e.g. with the network communication between ROS PC and rc_visard?
AFAIR we had this issue from the beginning, with every driver and firmware versions up to the latest ones. We have two identical robot work cells with the same setup and both have a rc_visard 160 that expose this issue. 

Thanks

**Comment by flixr** [comment]
The rc_visard_driver uses [rc_genicam_api](https://github.com/roboception/rc_genicam_api) to get the images via GigE Vision which is based on UDP so packets can get lost and a re-transmit requested.

In most cases this is simply solved by enabling jumbo frames (increasing the MTU to 9000) and increasing receive buffer size on the host running the driver, see https://github.com/roboception/rc_genicam_api#network-optimization-under-linux

If you have the rc_visard connected not directly but via a switch, make sure the switch can handle the burst packets and supports a MTU of 9000. Enabling pause frames in the switch might also help if the switch is dropping packets.

The rc_visard_driver is also printing the actually used packet size at startup (should be 9000 if you enabled jumbo frames).

**Comment by wiewo** [comment]
Enabling jumbo frames on the host and on all switches inbetween solved the issue.
Thanks for the hints!
