### ISSUE TITLE
which color topic maps the depth topic?

### ISSUE THREAD

**Issue by hygxy** [roboception/rc_visard_ros#14]
Hey, i've noticed that for color images there are two published topics:
- /stereo/left/image_rect_color
- /stereo/right/image_rect_color

from the names i suppose that they are all rectified. Here is my question: which one above has a 1:1 mapping with the depth topic : -/stereo/depth?  i.e. , depth(x,y) represents the depth value of point in color(x,y).

Thanks in advance!

**Comment by flixr** [comment]
Disparity, confidence, error and depth images all map to the left camera image.

See also
* https://github.com/roboception/rc_visard_ros/tree/master/rc_visard_driver#relevant-coordinate-frames
* https://doc.rc-visard.com/latest/en/stereo_matching.html#computing-disparity-images

**Comment by hygxy** [comment]
Hello, I want to ask another question(I could have written an email to the support team, but maybe others have the same question):

Is it possible to get the color ros topic of 640x480 resolution without affecting the field of view? right now the color ros topic "/stereo/left/image_rect_color" is of resolution 1280x960.
I could have this done by calling resize APIs from vision library like OpenCV, but I am afraid that it will affect the field of view so that the focal length can not be obtained by multiplying focal length factor by the image width/height.

The reason for this question is that I want the depth and color topic of the same resolution size 640*480

**Comment by flixr** [comment]
You can just downscale the image to 640x480, for that resolution the aspect ratio won't change.
The FocalLengthFactor is still valid then.
If you already have the image in ROS, you can also use e.g. the resize nodelet from [image_proc](http://wiki.ros.org/image_proc), which will also correctly update the focal length in the camera info.

**Comment by hygxy** [comment]
But according to this [issue](https://github.com/roboception/rc_visard_ros/issues/6#issuecomment-389845148), the raw image output is not available and [image_proc](http://wiki.ros.org/image_proc) is responsible for converting the raw image output to undistorted ones. Can the "/stereo/left/image_rect_color" topic just be the input of [image_proc](http://wiki.ros.org/image_proc)?

**Comment by flixr** [comment]
The image_proc/resize only resizes, without rectification (you already have a rectified image).
image_proc/crop_decimate could also be used (e.g. if you also want to crop)...
