### ISSUE TITLE
camera_params_publisher dependency issue

### ISSUE THREAD

**Issue by DHeroPlasma** [roboception/rc_visard_ros#15]
When trying to compile the rc_visard_driver, the following error appears:

catkin_ws/src/rc_visard_ros/rc_visard_driver/src/publishers/camera_params_publisher.h:40:10: 
fatal error: rc_common_msgs/CameraParams.h: No such file or directory
 #include <rc_common_msgs/CameraParams.h>

I am aware that there has been a commit recently where you changed the include-tag, but it appears that the issue has not been fixed for all files.
I managed to circumvent this by checking out an older version from git

**Comment by flixr** [comment]
Thanks for the info, pushed the missing commits...
