### ISSUE TITLE
rc_visard_driver: Received incomplete image buffer

### ISSUE THREAD

**Issue by Cmeo97** [roboception/rc_visard_ros#16]
Hi!

I was trying to follow this tutorial: http://wiki.ros.org/rc_visard/Tutorials/FirstSteps
However, once I run rviz, the refresh rate of images is really slow. Moreover, the terminal where I run the node prints every second: rc_visard_driver: Received incomplete image buffer.

I looked this problem online and I found some solutions to it. 
For example I changed mtu value to 9000 ( I did sudo ifconfig eno1 mtu 9000), then I changed the net.core.rmem_max value ( I did sudo sysctl -w net.core.rmem_max=99954432), I also tried sudo sysctl -w net.core.netdev_budget=600
and sudo sysctl -w net.core.netdev_max_backlog=2000 . 

However, when the problem is not fixed and if I do netstat -anus I get: 
IcmpMsg:
    InType0: 2
    InType3: 241
    OutType3: 2527
    OutType8: 2
Udp:
    35544038 packets received
    1335930 packets to unknown port received
    704 packet receive errors
    12363162 packets sent
    704 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 59
UdpLite:
IpExt:
    InMcastPkts: 206
    OutMcastPkts: 196
    InBcastPkts: 59
    OutBcastPkts: 53
    InOctets: 259529985789
    OutOctets: 5518228073
    InMcastOctets: 32556
    OutMcastOctets: 20255
    InBcastOctets: 4661
    OutBcastOctets: 2693
    InNoECTPkts: 50600537

I also tried ./net_perf_check.sh, which prints: 
MTU
  MTU of eno1 is sufficient (Current value: 9000)

RMEM_MAX
  There were 704 RcvbufErrors, consider reviewing rmem_max tunable. (Current value: net.core.rmem_max = 99954432)
  This is only a problem if RcvbufErrors value increases while receiving data.

SOFTIRQ
  Backlog max is sufficient (Current value: net.core.netdev_max_backlog = 2000)
  Budget is sufficient (Current value: net.core.netdev_budget = 600)

Finally, while the online interface is able to show camera images with a rate of 25Hz, the topic in ROS is published with a rate of 0.132, and the message is not always published. It actually print 20 times: message not received, and one out of 20 times, Rate 0.132 Hz. I also tried to use compressed topics, but it didn't work as well. 
What can I do? please help me.

**Comment by flixr** [comment]
My guess would be that you have another GenTL producer installed and that is picked or you are (maybe by accident) using a wifi connection.
Please make sure that the `GENICAM_GENTL64_PATH` is either unset or set to the GenTL producer shipped with rc_genicam_api.
See also https://github.com/roboception/rc_genicam_api#finding-the-transport-layer
You can use the [`gc_info` tool](https://github.com/roboception/rc_genicam_api#gc_info) to print the found/used producer: `gc_info -l`. It should point to either the one shipped with rc_genicam_api (e.g. for the package from the ROS buildfarm `/opt/ros/melodic/lib/rc_genicam_api/libbgapi2_gige.cti`).

**Comment by Cmeo97** [comment]
I checked GENICAM_GENTL64_PATH, it is unset. I have never had problem with the transport layer error which is indicated here: 'No transport layers found in path /usr/lib/rc_genicam_api' . 
The connection is through Ethernet port. 
This is the output of gc_info -l

gc_info -l
Transport Layer /opt/ros/melodic/lib/rc_genicam_api/libbgapi2_gige.cti_2.9.22968.22969
Vendor:         Baumer
Model:          bgapi2_gige
Vendor version: 2.9.22968.22969
TL type:        GEV
Name:           libbgapi2_gige.cti
Pathname:       /opt/ros/melodic/lib/rc_genicam_api/libbgapi2_gige.cti
Display name:   Baumer GEV TL
GenTL version   1.5

    Interface     eno1
    Display name: eno1
    TL type:      GEV

        Device             devicemodul00_14_2d_2c_dd_6b
        Vendor:            Roboception GmbH
        Model:             rc_visard 160c
        TL type:           GEV
        Display name:      rc_visard 160c
        User defined name: 
        Access status:     NoAccess
        Serial number:     02940267
        Version:           
        TS Frequency:      0

    Interface     wlo1
    Display name: wlo1
    TL type:      GEV

Transport Layer /opt/ros/melodic/lib/rc_genicam_api/libbgapi2_usb.cti_2.9.22669.22969
Vendor:         Baumer
Model:          bgapi2_usb
Vendor version: 2.9.22669.22969
TL type:        U3V
Name:           libbgapi2_usb.cti
Pathname:       /opt/ros/melodic/lib/rc_genicam_api/libbgapi2_usb.cti
Display name:   Baumer U3V TL
GenTL version   1.5

    Interface     USB
    Display name: USB HOST
    TL type:      U3V

I am not understanding how to solve the problem . please help me

**Comment by flixr** [comment]
Ok, so it's using the correct GenTL producer...
Did you check the link speed and the cable?
You can see the link speed (which should be 1000, so 1GBit) in the WebGUI on the system page.
At the bottom of the system page you can also see some GigE Vision statistics, it should not show any dropped frames and only a few (if any) resends. Packet size should be 9000 (same as the rc_visard_driver should print at the beginning).

**Comment by Cmeo97** [comment]
![Schermata del 2021-03-18 16-53-12](https://user-images.githubusercontent.com/56228016/111656304-b012ba80-880a-11eb-8e48-265e2a92faad.png)


[
![Schermata del 2021-03-18 16-57-41](https://user-images.githubusercontent.com/56228016/111656868-34fdd400-880b-11eb-96bc-30d8d70eed45.png)
![Schermata del 2021-03-18 16-53-29](https://user-images.githubusercontent.com/56228016/111656870-35966a80-880b-11eb-9a33-7b3771c32777.png)

](url)

**Comment by Cmeo97** [comment]
Do you mean these ones? Because I'm not really sure. Connection options show a velocity of 1000Mb/s, but the driver process seems to go at 34,0 MiB.

**Comment by flixr** [comment]
I meant the rc_visard WebGUI:
https://doc.rc-visard.com/latest/en/webgui.html

You can also download add logs there on the logs page and send them to support@roboception.de and we can have a look...

**Comment by Cmeo97** [comment]
![Schermata del 2021-03-18 17-07-07](https://user-images.githubusercontent.com/56228016/111658194-688d2e00-880c-11eb-8cb1-9641902c8540.png)

**Comment by Cmeo97** [comment]
Do you mean this one?

**Comment by Cmeo97** [comment]
![Schermata del 2021-03-18 17-09-25](https://user-images.githubusercontent.com/56228016/111658530-b6a23180-880c-11eb-8f7a-7bccc7eba7fc.png)
Maybe this one

**Comment by flixr** [comment]
Yes... uii... lots of packet resends... do you have a router/switch or something in between or is the rc_visard directly connected?

If you send the tarball (download all logs on logs tab in WebGUI) to support@roboception.de we could also quickly check if we see anything suspicious in there.

**Comment by Cmeo97** [comment]
I sent you the log files! Thanks  a lot!

**Comment by flixr** [comment]
So the rc_visard receives a LOT of pause frames which essentially tells it to briefly stop sending data.
This usually happens if you have a switch in between that is overwhelmed with the amount of data (or your PC/Laptop sends this if there is no other network device in between).
So if you have a switch in between, please connect it directly and check if it works correctly then. If that is the case, get a more powerful switch or keep it directly connected...

**Comment by Cmeo97** [comment]
It is connected directly

**Comment by flixr** [comment]
Do you maybe have a high CPU usage so that the rc_visard_driver doesn't get enough time scheduled to read all the packets?

On a side-node: there are newer firmware images available at https://roboception.com/en/download/

**Comment by Cmeo97** [comment]
The CPU usage is about 20% , I have an intel core i7 12-core.

**Comment by Cmeo97** [comment]
Once I download the new firmware, what should I do? How can I install it?

**Comment by flixr** [comment]
For posterity: The firmware can be updated through the WebGUI:
https://doc.rc-visard.com/latest/en/maintenance.html#updating-the-firmware

I'll close this issue here now, as we'll handle it through support from here on as it doesn't look like it's a problem with the rc_visard_driver...
