### ISSUE TITLE
Only nan values array after parsing of an depth image message

### ISSUE THREAD

**Issue by LukasEdl** [roboception/rc_visard_ros#17]
Hi everyone,
i am currently getting a depth image over the /stereo/depth topic. However, if I try to convert the data into a float32 array using numpy or the imgmsg_to_cv2 method of the cvbridge, i get an array full of nan values.

Do you have some ideas, or examples, how to convert the data of the image message into a numpy array which can be used further?

I'm using the python 2.7 64-Bit interpreter.

**Comment by heikohimu** [comment]
NaN is used in ROS depth images for missing / invalid values. Some pixels of the depth image will always be invalid, but there should be also valid values contained in your array. Can you check that?

**Comment by LukasEdl** [comment]
Hi @heikohimu,
thanks for the quick response. There were actually values in the array, i just did not see them.

I going to close that ticket.
