### ISSUE TITLE
ROS2 porting

### ISSUE THREAD

**Issue by cco-seasony** [roboception/rc_visard_ros#18]
Hi!
Are there any plans on porting this driver to ROS2?

Kind regards,
Carlos

**Comment by flixr** [comment]
We are deprecating the packages in this repository soon in favor of more generic drivers that also work for our rc_cube.

The **rc_visard_driver** has been superseded by **rc_genicam_driver** which is available for ROS1 and ROS2:
https://github.com/roboception/rc_genicam_driver_ros
https://github.com/roboception/rc_genicam_driver_ros2

Similarly for the clients please take a look at
https://github.com/roboception/rc_reason_clients_ros
https://github.com/roboception/rc_reason_clients_ros2

Please let us know if you miss some functionality in the new driver/client nodes.
