### ISSUE TITLE
Cloning the refferenced repos

### ISSUE THREAD

**Issue by dkanou** [roboception/rc_visard_ros#2]
I have an issue when cloning the particular REPO.  There are folders where the dependant REPOS (such as: rc_dynamics_api,  rc_genicam_api, rc_dynamics_msgs as well as the external: CPR and JSON).  For some reason: git clone git@github.com:roboception/rc_visard_ros.git leaves all the corresponding folders empty.

Notice that when I manually copy all these REPOs in the right folders, the whole project compiles smoothly.

**Comment by heikohimu** [comment]
Please have a look at rc_visard_driver/README.md in section 'Build/Installation', i.e. after cloning just do:

git submodule update --init --recursive

**Comment by dkanou** [comment]
Worked smoothly!  Thanks!
