### ISSUE TITLE
rosrun rc_visard_driver causes error message

### ISSUE THREAD

**Issue by matthias-schleibinger** [roboception/rc_visard_ros#7]
The start of the ROS node rc_visard_driver doesn't work anymore. If I run 
`rosrun rc_visard_driver rc_visard_driver`
from the command line two error messages appear.

![anhang_1](https://user-images.githubusercontent.com/27730752/43310453-e23be756-9187-11e8-953a-a0f53cb48615.png)

It did work previously, but since this week the aforementioned error messages appear and the node doesn't start.
In the meantime I updated my system via:
`sudo apt-get update`
`sudo apt-get dist-upgrade`
but I don't know whether the problem started right after it or if something else caused it.

The library mentioned in the error message exists:

![anhang_3](https://user-images.githubusercontent.com/27730752/43311348-7d2dd420-918a-11e8-8a29-fe5bfa41f786.png)

System information and Software versions:
OS: Ubuntu 16.04
ROS: Kinetic
rc_visard_driver: 2.2.0
rc_genicam_api: 1.3.11
rc_dynamics_api: 0.7.0
Sensor firmware: rc_visard_v1.0.8

I didn’t compile the driver from source, but installed its debian package:
`sudo apt-get install ros-kinetic-rc-visard-driver`

**Comment by flixr** [comment]
This is strange, the packages built on the ROS buildfarm work as expected here as well as in a fresh kinetic environment.

My guess would be that you have some problem with your environment setup or similar.

Could you please verify that you really have these package versions installed?
E.g. output of `apt-cache policy ros-kinetic-rc-visard-driver ros-kinetic-rc-dynamics-api ros-kinetic-rc-genicam-api`.

Also the symbol `_ZN11roboception4msgs10Trajectory17default_instance_E` that was apparently missing should be contained in `librc_dynamics_api`.
You can check that with `readelf -Ws /opt/ros/kinetic/lib/librc_dynamics_api.so | grep -i Trajectory17default_instance_E`

**Comment by matthias-schleibinger** [comment]
The versions of the installed packages should be the ones mentioned above. Here is the output of `apt-cache policy ros-kinetic-rc-visard-driver ros-kinetic-rc-dynamics-api ros-kinetic-rc-genicam-api`:

![anhang_4](https://user-images.githubusercontent.com/27730752/43316708-6bee0e2c-919a-11e8-89b1-d9e8a94ce75c.png)

The missing symbol apparently exists, too.

![anhang_5](https://user-images.githubusercontent.com/27730752/43316904-1ec9e836-919b-11e8-9110-66a30f467f2c.png)

I am fairly new to ROS, but, as far as I know, I have not changed my environment setup recently. Additionally all my other self-programmed nodes seem to work.

**Comment by flixr** [comment]
Do you maybe have another version of `librc_dynamics_api.so` locally somewhere in your workspace (or your `LD_LIBRARY_PATH`)?

**Comment by matthias-schleibinger** [comment]
There is no other version of `librc_dynamics_api.so` in my workspace, but in fact there is one in my `LD_LIBRARY_PATH`:

![anhang_6](https://user-images.githubusercontent.com/27730752/43323325-9c779fa6-91b1-11e8-8600-87c5a95f9619.png)

Both, `/usr/local/lib` and `/opt/ros/kinetic/lib` are in my `LD_LIBRARY_PATH`

**Comment by flixr** [comment]
So which of those comes first in `LD_LIBRARY_PATH`? The first one is loaded... and my guess is that it is the one in `/usr/local/lib` and that that one is outdated.
So remove the ones in `/usr/local/lib` which must be from an older version which was installed from source.

**Comment by matthias-schleibinger** [comment]
Your guess is right, `/usr/local/lib` is mentioned first in the `LD_LIBRARY_PATH`.

**I deleted both `librc_dynamics_api.so` and `librc_dynamics_api.so.0.7` from `/usr/local/lib`.**

The node can be started again and is working. Thank you very much for your help. 


You can close this issue now or you can tell me how you knew that the problem was concerning `librc_dynamics_api.so`, although it wasn't mentioned in the error message? Just wondering whether I should have been able to solve this problem on my own...

**Comment by flixr** [comment]
From the error message you got it was already clear which symbol could not be loaded. The question then is just why.
So two steps:
1. find out which library *should* have this symbol
2. find out why that lib doesn't have it (usually wrong version of the lib)

In my case I already knew from the symbol name that it had to be in the rc_dynamics lib.
But next time you have problems like this you can also check which libs are loaded by the one mentioned in the error message:
`ldd /opt/ros/kinetic/lib/librc_visard_driver_nodelet.so | grep librc`
You can then just check which library has this symbol by dumping the symbols of them with e.g. readelf as shown before.
As the symbol was there in `/opt/ros/kinetic/lib/librc_dynamics_api.so`, it had to be missing in a so with the same name somewhere else.
