### ISSUE TITLE
Cannot find library when building package

### ISSUE THREAD

**Issue by Minimartian** [roboception/rc_visard_ros#8]
Hello, I am trying to build the rc_visard_ros package, but I am getting the following error:

[ 36%] Linking CXX shared library ../devel/lib/librc_visard_driver_nodelet.so
/usr/bin/ld: cannot find -lGCBase_gcc42_v3_1
/usr/bin/ld: cannot find -lMathParser_gcc42_v3_1
/usr/bin/ld: cannot find -lGenApi_gcc42_v3_1
/usr/bin/ld: cannot find -lNodeMapData_gcc42_v3_1
/usr/bin/ld: cannot find -llog4cpp_gcc42_v3_1
/usr/bin/ld: cannot find -lXmlParser_gcc42_v3_1
/usr/bin/ld: cannot find -lLog_gcc42_v3_1
collect2: error: ld returned 1 exit status
src/CMakeFiles/rc_visard_driver_nodelet.dir/build.make:472: recipe for target 'devel/lib/librc_visard_driver_nodelet.so' failed
make[2]: *** [devel/lib/librc_visard_driver_nodelet.so] Error 1
CMakeFiles/Makefile2:3247: recipe for target 'src/CMakeFiles/rc_visard_driver_nodelet.dir/all' failed
make[1]: *** [src/CMakeFiles/rc_visard_driver_nodelet.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

I am using ROS kinetic on 16.04

Do you have any advice for this? Thank you

**Comment by Minimartian** [comment]
You can close this issue. I had installed the rc_genicam_api and rc_dynamics_api in the wrong location (needed to be /usr/lib/).

**Comment by heikohimu** [comment]
ok

**Comment by flixr** [comment]
Should be fixed with https://github.com/roboception/rc_visard_ros/commit/4e6fd568e8697199e2e90f6e00cec1e58e87f80b
