### ISSUE TITLE
Regression on Lunar and Melodic

### ISSUE THREAD

**Issue by clalancette** [roboception/rc_visard_ros#9]
This package currently has a regression in both Lunar and Melodic: http://repositories.ros.org/status_page/ros_melodic_default.html?q=REGRESSION and http://repositories.ros.org/status_page/ros_lunar_default.html?q=REGRESSION .  There are actually a couple of different problems:

1.  rc_visard now depends on rc_hand_eye_calibration_client.  rc_hand_eye_calibration_client is failing to [build](http://build.ros.org/job/Lbin_uX64__rc_hand_eye_calibration_client__ubuntu_xenial_amd64__binary/3/consoleFull) because of a missing dependency on OpenSSL .  Adding a `<depend>` in rc_hand_eye_calibration_client package.xml may fix this.
1.  rc_visard_driver is failing because it is failing the final link step: http://build.ros.org/view/Lbin_uX64/job/Lbin_uX64__rc_visard_driver__ubuntu_xenial_amd64__binary/21/console .  I'm not entirely sure what the is going on with that failure, but it bears looking into.

I'd like to do a sync of Lunar and Melodic next week, so any attention here would be appreciated.  If we don't get it resolved by sometime next week, I'll probably go back to an older version of rc_visard for the sync.

Thanks!

**Comment by tfoote** [comment]
This is also affecting Indigo and Kinetic.

**Comment by flixr** [comment]
Should be fixed with 2.4.2:
* https://github.com/ros/rosdistro/pull/19366
* https://github.com/ros/rosdistro/pull/19367
* https://github.com/ros/rosdistro/pull/19368
* https://github.com/ros/rosdistro/pull/19370
